Repository Bi-Ma-GOoOD/DiddyLearning, pull requests merged in 2025-03, with the labels that each got.

#7 start-using-pretrained-model
  .gitignore
  DiddyLearning.ipynb
  Model/DiseaseRice.ipynb
Labels: bug

#8 add-numClasses-stairLR-and-fillMode
  Model/DiseaseRice.ipynb
Labels: enhancement

#11 diddy baby oil
  Model/DiseaseRice.ipynb
  Scripts/DiseaseRice.ipynb
  Scripts/test.ipynb
Labels: enhancement

#14 first step
  .gitignore
  Scripts/DiseaseRice.ipynb
  Scripts/data_prepare.ipynb
  Scripts/test.ipynb
  Scripts/train.ipynb
  model/runs/detect/best_model/args.yaml
  model/runs/detect/best_model/events.out.tfevents.1741593735.DESKTOP-BGNJHTC.14688.2
  model/runs/detect/best_model/results.csv
  model/runs/detect/path_testing_model/args.yaml
  model/runs/detect/path_testing_model/events.out.tfevents.1741598334.DESKTOP-BGNJHTC.17892.1
  model/runs/detect/path_testing_model2/args.yaml
  model/runs/detect/path_testing_model2/events.out.tfevents.1741598348.DESKTOP-BGNJHTC.17892.2
  model/runs/detect/path_testing_model2/results.csv
Labels: enhancement, good first issue

#19 finished-final-DL-project
  Image_step_project/afterExtractZip.png
  Image_step_project/changePath.png
  Image_step_project/changePathinTrain.png
  Image_step_project/changeProjectSavePath.png
  Image_step_project/datadotyam.png
  Image_step_project/inVisualStudioCode.png
  Image_step_project/lastPredict.png
  Image_step_project/modelEval.png
  Image_step_project/modelTraining.png
  Image_step_project/parameterSaveAndName.png
  Image_step_project/predict.png
  README.md
Labels: documentation, enhancement
